name: CI/CD (Docker Hub)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest -q

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: pavanyarrapgada03
          password: dckr_pat_LqRK5QwPhWkdETIKXwyzom5xvRU
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: pavanyarrapragda03/flask-cicd:latest
